default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: microverse
  password: '01012020'
  database: desafio_ruby_on_rails

development:
  <<: *default
  database: desafio_ruby_on_rails_development

test:
  <<: *default
  database: desafio_ruby_on_rails_test

production:
  <<: *default
  database: desafio_ruby_on_rails_production
  # username: desafio_ruby_on_rails
  # password: <%= ENV['FACEBOOK_CLONE_PROJECT_DATABASE_PASSWORD'] %>
